### ISSUE TITLE
Add the clipboard package

### ISSUE THREAD

**Issue by Slackadays** [ublue-os/boxkit#21]
I'm searching GH for all mentions of wl-clipboard and I came across https://github.com/ublue-os/boxkit/commit/347647ea7f9f7bdb3b42d2a565df866f027a7ade. Adding `wl-clipboard` limits the usefulness of copying things with boxkit to just Wayland systems, which isn't very inclusive. My project Clipboard has an Alpine package and works on X11/Wayland/headless, and so including it here would allow boxkit to work with all those systems and not just Wayland ones. I hope this helps! :)

**Comment by castrojo** [comment]
Sounds awesome! What's the package name?

**Comment by EinoHR** [comment]
Interesting project!
_Though I can't help at feel a bit suspicous at this. It kind of feels dishonest going around Github promoting your project by searching for a rival packages name in different projects source code. Especially when you're not using those projects yourself. Just a thought._

**Comment by EinoHR** [comment]
@castrojo 

https://repology.org/project/clipboard/versions

**Comment by Slackadays** [comment]
> Though I can't help at feel a bit suspicous at this. It kind of feels dishonest going around Github promoting your project by searching for a rival packages name in different projects source code. Especially when you're not using those projects yourself. Just a thought.

I'm just making full use of the tools available on GH to make sure as many people are helped as possible. The only reason I made Clipboard because I got burned by xclip and wl-clipboard being unmarketed and leaving me without a way to copy stuff in the terminal and I don't want anybody else to experience that.

**Comment by castrojo** [comment]
Yeah adding it isn't a problem at all! I do get an error though when trying to use it in a distrobox:

```
Opening libclipboardx11.so to look for setX11Clipboard failed, aborting ope
Specific error: Error loading shared library libclipboardx11.so: No such file or directory
Opening libclipboardwayland.so to look for setWaylandClipboard failed, aborting operation
```

I don't see any extra packages to install, am I missing something?

**Comment by Slackadays** [comment]
Whoever made that package made an error then, as that's a debug message that you should only see if you're making it in debug mode. I'll contact the package maintainer and see if it can be fixed.

**Comment by Slackadays** [comment]
@castrojo The Alpine packages have been updated, see https://pkgs.alpinelinux.org/packages?name=clipboard

Now CB should work great! :rocket:

**Comment by castrojo** [comment]
Awesome, I'll start using it! 

This image is still 3.17 but I'll start an `:edge` one and add it. I'll keep this issue open as a reminder to myself.

**Comment by castrojo** [comment]
I've PRed alpine edge to the toolbox community repo, once it's merged I'll work on this further.

**Comment by castrojo** [comment]
Alright it's in there, thanks for the great tool!
