### ISSUE TITLE
Install repos with curl or git

### ISSUE THREAD

**Issue by FergusFettes** [ublue-os/boxkit#45]
Maybe I'm being dense, but it isn't immediately obvious to me how to install something with curl or git.

Trying to setup oh-my-zsh for example, most of the install scripts burn something into the `$USER/.local` directory, but since this is /root/ on build, it gets lost.

For example, to get oh-my-zsh, antigen and enhancd setup I need these three things:
```
RUN curl -L --create-dirs git.io/antigen ~/.config/antigen.zsh
RUN curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
RUN git clone https://github.com/b4b4r07/enhancd 
```

and I think there are in general a lot of 'packages' that are just a git clone or curl command away.

Enjoying the idea so far though, hope I can move to using this full time!

**Comment by FergusFettes** [comment]
I also tried getting clever with installing IPFS from other images, but this doesn't seem to work either:
```
FROM ctheory/alpine-ipfs:latest
FROM ghcr.io/fergusfettes/shell:latest

# Copy the binary from the previous stage
COPY --from=0 /usr/local/bin/ipfs /usr/bin/ipfs
```

**Comment by castrojo** [comment]
Yeah the one thing to remember is that the home directory is mapped to the user's home when you run the distrobox so a bunch of things that would work interactively won't work when making the box in github. 

I've found that some of those "curl | bash" style scripts sometimes might have an option to install at the system level, so if it has that option (and an unattended flag) then that'd probably work. Or you might need to modify the installation script to install the `/usr/bin` instead or whatever. 

I usually copy right from the container in one line, this is how I do kubectl and other go programsb. For IPFS I think this should work:

    COPY --from=ctheory/alpine-ipfs:latest /usr/local/bin/ipfs /usr/bin/ipfs

**Comment by FergusFettes** [comment]
Ah that was my bad, I didn't repull the image. So install to `/usr/bin/` works-- I just need to get as much as possible in there.

Thanks!
