### ISSUE TITLE
Package build failing

### ISSUE THREAD

**Issue by dvogeldev** [ublue-os/boxkit#60]
I'm using a forked build. I have changed the cosign keys and assigned a finegrain token to the repo with ALL groups set to Read/Write.

The Release builds, the Package build fails with the following error:
"Error: writing blob: initiating layer upload to /v2/dvogeldev/boxkit/blobs/uploads/ in ghcr.io: denied: permission_denied: write_package"

No other changes were made to the codebase other than a change to the repo name.

What am I missing? Thank you

**Comment by castrojo** [comment]
Double check the permissions in your github repo settings -> Actions -> General. Here's what mine looks like:

![image](https://github.com/ublue-os/boxkit/assets/1264109/60670600-6ebd-48c5-b117-47ae0c0a30f3)

**Comment by dvogeldev** [comment]
I believe my problem was related to my github settings. I went ahead and created a new GitHub account from scratch and was able to create a customized package.

One problem was I forgot to rename the image in .github/workflows/build-boxkit.yml

Thank you for taking the time to help.
